// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";

export const isSupabaseConfigured = Boolean(
  SUPABASE_URL &&
    SUPABASE_ANON_KEY &&
    SUPABASE_URL.startsWith("http")
);

// Prevent production blank screen when env vars are missing on static hosting.
const safeSupabaseUrl = isSupabaseConfigured
  ? SUPABASE_URL
  : "https://placeholder.supabase.co";
const safeSupabaseAnonKey = isSupabaseConfigured
  ? SUPABASE_ANON_KEY
  : "public-anon-key-placeholder";

if (!isSupabaseConfigured && typeof window !== "undefined") {
  console.warn(
    "Supabase non configuré: VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY manquants."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(safeSupabaseUrl, safeSupabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
